; PlatformIO Project Configuration File
;
; ESP32-S3: Display + Battery + UART bridge to C5

[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32-s3-devkitc1-n16r8
framework = espidf
board_build.flash_size = 16MB
board_build.partitions = partitions_16MB.csv
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder
upload_speed = 921600

build_flags =
    -Os
    -DCONFIG_IDF_TARGET_ESP32S3=1
